name: general_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - seaborn=0.13.2
  - numpy=1.26.0
  - tqdm=4.66.2
  - numba=0.59.1
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - matplotlib=3.8.0
  - ipython=8.15.0
  - ipykernel=6.25.0
  - pip:
    - ucimlrepo
